// End of Skill code -------------------------------------------------------------
// Static Language Model for reference
module.exports.model = {
  interactionModel: {
    languageModel: {
      intents: [
        {
          name: 'getCategoryBalance',
          slots: [
            {
              name: 'category',
              type: 'CATEGORY',
            },
            {
              name: 'date',
              type: 'AMAZON.DATE',
            },
          ],
          samples: [
            'How much I spent on Beauty',
            'Get my category balance for Beauty category',
            'Get my category balance for January',
            'How much did I spend on Beauty category January',
            'How much did I earn on Extra Income category January',
            'How much did I spend on restaurant category',
            'How much did I earn on salary category',
            'Whats the balance of groceries category for January',
            'Whats the balance of groceries category',
            'What is the balance of  groceries category',
            'How much did I earn on extra income',
            'How much did I spend on party ',
            "What's the balance of bills",
          ],
        },
        {
          name: 'addNewTransaction',
          slots: [
            {
              name: 'number',
              type: 'AMAZON.NUMBER',
              samples: ['One'],
            },
            {
              name: 'currency',
              type: 'CURRENCY',
            },
            {
              name: 'categories',
              type: 'CATEGORY',
              samples: ['{categories}'],
            },
            {
              name: 'date',
              type: 'AMAZON.DATE',
            },
          ],
          samples: [
            'Add a transaction with One Euro in {categories} category',
            'Add a transaction for {categories}',
            'Add a transaction with One Euro for {categories} category',
            'Add a transaction with One Euro for {categories}',
            'Add a transaction with One Euro in {categories} category for the January ',
            'Add a transaction with One Euro in {categories} category for January',
            'Add a transaction with One Euro in {categories}',
            'Add a transaction with One Euro',
            'Add a new transaction with One Euro in {categories} category for January',
            'Add a new transaction with One Euro in {categories} category for the February',
            'Add a new transaction with One Euro in {categories} category',
            'Add a new transaction with One Euro for {categories} category',
            'Add a new transaction for One Euro February',
            'Add a new transaction with One',
            'Add a new transaction with One Euro February',
            'Add a new transaction with One Euro',
            'Add a new transaction for {categories}',
            'Add a new transaction of {categories} for One Euro',
            'I spent One Euro February on {categories}',
            'I earned One Euro February on {categories}',
            'I received One Euro February on {categories}',
            'I just received One Euro on {categories}',
          ],
        },
        {
          name: 'changeDefaultWallet',
          slots: [
            {
              name: 'wallet',
              type: 'CURRENCY',
              samples: ['{wallet}'],
            },
          ],
          samples: [
            'Change default wallet to {wallet}',
            'Change the default wallet to {wallet}',
            'I want to change my default wallet to {wallet}',
            'Change my default wallet to {wallet}',
          ],
        },
        {
          name: 'changeDefaultAccount',
          slots: [
            {
              name: 'account',
              type: 'AMAZON.SearchQuery',
              samples: ['HSBC'],
            },
          ],
          samples: [
            'Change my default account to HSBC instead',
            'My default account is HSBC',
            'Change default account to HSBC',
            'Change the default account to HSBC',
            'I want to change my default account to HSBC',
            'Change my default account to HSBC',
          ],
        },
        {
          name: 'addNewBudget',
          slots: [
            {
              name: 'category',
              type: 'CATEGORY',
              samples: ['learning category', 'learning'],
            },
            {
              name: 'amount',
              type: 'AMAZON.NUMBER',
            },
            {
              name: 'currency',
              type: 'CURRENCY',
            },
          ],
          samples: [
            'Add a budget for learning category for One Euro ',
            'Add a new budget for learning category for One Euro',
            'Add a budget with learning category',
            'Add a new budget for learning category',
            'Add a new budget with learning category for One Euro',
            'Add a budget with learning category for One Euro ',
            'Add a new budget in learning',
            'Add a new budget with learning',
            'Add a new budget with miscellaneous category',
            'Add a budget in groceries category for One Euro',
            'Add a new budget in groceries category for One Euro',
            'Add a budget in groceries category',
            'Add a new budget in groceries category ',
            'Add a budget for groceries',
            'Add a budget of One  Euro  for groceries',
            'Add a budget of One for groceries',
            'Add a budget for One Euro',
            'Add a budget for One',
            'Add a new budget for One',
            'Add a new budget for One Euro',
            'Add a new budget of One for groceries',
            'Add a new budget of One  Euro  for groceries ',
            'Add a new budget for groceries',
          ],
        },
        {
          name: 'addNewGoal',
          slots: [
            {
              name: 'goaltype',
              type: 'GOAL_TYPE',
            },
            {
              name: 'amount',
              type: 'AMAZON.NUMBER',
              samples: [
                'I want my target amount to be One Euro',
                'One Euro',
                'I want my target amount to be One',
                'One',
              ],
            },
            {
              name: 'currency',
              type: 'CURRENCY',
            },
            {
              name: 'monthlyContribution',
              type: 'AMAZON.NUMBER',
              samples: [
                'I want my monthly conribution to be One Euro',
                'I want my monthly conribution to be One ',
                'I want to contribute One Euro',
                'I want to contribute One',
                'One',
                'One Euro',
              ],
            },
            {
              name: 'targetDate',
              type: 'AMAZON.DATE',
              samples: [
                'I want to fulfil my goal by {targetDate}',
                '{targetDate}',
              ],
            },
          ],
          samples: [
            'Add a new goal with a monthly contribution of One Euro',
            'Add a goal with a monthly contribution of One Euro',
            'Add a Improve my home goal with a target amount of One Euro with a target date of {targetDate} and a monthly contribution of One ',
            'Add a Improve my home goal with a target amount of One Euro with a target date of {targetDate}',
            'Add a new Improve my home goal with a target amount of One Euro with a target date of {targetDate}',
            'Add a new goal with a target amount of One Euro with a target date of {targetDate}',
            'Add a goal with a target amount of One Euro with a target date of {targetDate}',
            'Add a goal for Improve my home with a goal of One Euro and a monthly contribution of One',
            'Add a goal for Improve my home with a target amount of One Euro',
            'Add a goal for Improve my home with One Euro',
            'Add a goal with a target date of {targetDate}',
            'Add a goal with a monthly contribution of One',
            'Add a goal with a target amount of One Euro',
            'Add a new goal with a target amount of One Euro',
            'Add a new goal with a final amount of One Euro',
            'Add a new goal for Improve my home with a goal of One Euro and a monthly contribution of One',
            'Add a new goal with a monthly contribution of One',
            'Add a new goal with a target date of Improve my home',
            'Add a new goal for Improve my home with One Euro',
            'Add a new goal for Improve my home with a goal of One Euro',
            'Add a new goal for Improve my home with a target amount of One Euro',
            'Add a new goal for Improve my home ',
          ],
        },
        {
          name: 'getBudgetBalance',
          slots: [
            {
              name: 'category',
              type: 'CATEGORY',
              samples: [
                'The balance of groceries category',
                'I would like to know the balance of groceries category',
                'I want to know the budget balance for groceries category',
                'groceries category',
                'groceries',
              ],
            },
          ],
          samples: [
            'Get my budget balance for groceries category',
            'Get budget balance for groceries category',
            'Get budget balance for groceries',
            'Tell my budget balance for groceries category',
            'Tell my budget balance for groceries',
            'Tell me my budget balance for groceries category',
            'Whats my budget balance for groceries category',
            'Whats the budget balance for groceries category',
            'Tell me my budget balance in groceries category',
            'Tell me my budget balance in groceries',
            'Whats the budget balance in groceries category',
            'Whats the budget balance in groceries',
            'Whats my budget balance in groceries category',
            'What is my budget balance in groceries category ',
            'Whats my budget balance in groceries',
          ],
        },
        {
          name: 'getTagBalance',
          slots: [
            {
              name: 'tag',
              type: 'AMAZON.SearchQuery',
              samples: [
                'I would like to know the balance for Monthly',
                'I want to know the balance of Monthly',
                'I would like to know the balance for Monthly tag',
                'I want to know the balance of Monthly tag',
                'Monthly tag',
                'Monthly',
              ],
            },
          ],
          samples: [
            'Get the tag balance for Monthly',
            'How much did I earn on Monthly tags',
            'How much did I spend on Monthly tags',
            'Tell me the expenditure of the Monthly tags',
            'Whats my Monthly tags balance',
            'Whats the Monthly tags balance',
            'Get the Monthly tags balance',
            'Get the Monthly tag balance',
            'Whats the Monthly tag balance',
            'Whats my Monthly tag balance',
            'Tell the Monthly tag balance',
            'Tel me the Monthly tag balance',
            'Tell me the Monthly tags earnings',
            'Tell me the Monthly tags expenditure',
            ' Tell me the expenditure of the Monthly tag',
            'Tell me the Monthly tags amount ',
            'How much did I spend on Monthly tag',
            'How much did I earn on Monthly tag',
          ],
        },
        {
          name: 'changeBudgetAmount',
          slots: [
            {
              name: 'category',
              type: 'CATEGORY',
              samples: ['groceries category', 'groceries'],
            },
            {
              name: 'currency',
              type: 'CURRENCY',
            },
            {
              name: 'amt',
              type: 'AMAZON.NUMBER',
              samples: [
                'The budget amount is One Euro',
                'I would like tha budget amount to be One Euro',
                'I would like tha budget amount to be One',
                'One Euro',
                'One',
              ],
            },
          ],
          samples: [
            'Change budget amount for groceries category',
            'Change budget amount for groceries',
            'Change my budget amount to One Euro for groceries category',
            'Change my budget amount to One Euro',
            'Change my budget amount to One Euro for groceries',
            'Change my budget amount to One',
            'Change the budget amount for groceries category',
            'Change the budget for groceries category',
            'Change the budget amount for rent',
            'Change the budget for rent',
            'Change budget to One Euro',
            'Change rent budget amount to One Euro',
            'Change rent budget amount to One',
            'Change the rent budget amount to One Euro',
            'Change the rent budget amount to One',
            'Change the rent budgets amount to One',
            'Change the rent budget to One',
            'Change the rent budgets amount to One Euro',
            'Change the rent budget to One Euro',
            'Change the budget amount of rent to One Euro',
            'Change the budget balance of rent to One',
          ],
        },
        {
          name: 'getDefaultWallet',
          slots: [],
          samples: [
            'Get default wallet',
            'Tell my default wallet',
            'Whats the default wallet',
            'Tell me my default wallet',
            'Whas my default wallet',
            'What is the default wallet',
            'What is my default wallet',
          ],
        },
        {
          name: 'getDefaultAccount',
          slots: [],
          samples: [
            'Get default account',
            'Tell my default account',
            'Tell me my default account',
            'Whats the default account',
            'Whats my default account',
            'What is the default account',
            'What is my default account',
          ],
        },
        {
          name: 'addNewWallet',
          slots: [
            {
              name: 'currency',
              type: 'CURRENCY',
              multipleValues: {
                enabled: true,
              },
            },
          ],
          samples: [
            'Add a new wallet for Euro currency',
            'Add a new wallet for Euro',
            'I want to add a new Euro wallet',
            'Add a Euro wallet',
            'Add new Euro wallet',
            'Add a new wallet with currency as Euro',
            'Can you add a Euro wallet',
            'Add a new Euro wallet',
          ],
        },
        {
          name: 'getBudgetAmount',
          slots: [
            {
              name: 'category',
              type: 'CATEGORY',
              samples: ['rent'],
            },
            {
              name: 'date',
              type: 'AMAZON.DATE',
            },
          ],
          samples: [
            'Get my budget amount for restaurant category',
            'Whats the amount for restaurant budget',
            'Whats the budget amount for restaurant',
            'Whats the budget for restaurant category',
            'Whats the restaurant budget amount',
            'What is the budget amount today',
            'What is the budget amount for today',
            'Whats the budget amount for today',
            'Whats the budget amount today',
            'Whats the restaurant budget amount today',
            'Whats the restaurant budget amount for  today',
            'Whats the restaurant budget',
            'Whats the budget for restaurant',
            'What is the budget amount for restaurant',
            'What is the budget for restaurant',
            'Whats the amount of restaurant budget for today',
          ],
        },
        {
          name: 'sendFeatureRequest',
          slots: [
            {
              name: 'search',
              type: 'AMAZON.SearchQuery',
              samples: ['add a new tag'],
            },
          ],
          samples: [
            'Send Blitz Budget a new feature to add a new tag',
            'Send a new feature to add a new tag',
            'Send a new feature for add a new tag',
            'Send a new feature request to add a new tag',
            'Send a new feature request for add a new tag',
            'Send Blitz Budget a feature request to add a new tag',
            'Send a feature request to add a new tag',
          ],
        },
        {
          name: 'getTransactionTotalByDate',
          slots: [
            {
              name: 'date',
              type: 'AMAZON.DATE',
              samples: ['today'],
            },
          ],
          samples: [
            'Whats my total transaction for today',
            'What is my total transaction for today',
            'Whats the total transaction for this year',
            'What is the total transaction this year',
            'Whats my total transaction this year',
            'What is the transaction total this month',
            'What is the transaction total for this month',
            'Whats the transaction total for this month',
            'What is my transaction total for this month',
            'What is my transaction total this month',
            'Whats my transaction total this month',
            'Whats my transaction total for this month',
          ],
        },
        {
          name: 'getEarningsByDate',
          slots: [
            {
              name: 'date',
              type: 'AMAZON.DATE',
              samples: ['this month'],
            },
          ],
          samples: [
            'Get my income today',
            'Get my income for this month',
            'What is my income this month',
            'Whats my income this month',
            'What is my total income this month',
            'Whats my total income this month',
            'How much did I earn this month',
          ],
        },
        {
          name: 'getExpenditureByDate',
          slots: [
            {
              name: 'date',
              type: 'AMAZON.DATE',
              samples: ['this month'],
            },
          ],
          samples: [
            'Get my expense for last month',
            'Get my expense last month',
            'How much did I spend in last month',
            'What is my expenditure last month',
            'Whats the expenditure last month',
            'What is the expenditure for last month',
            'Whats my expenditure last month',
            'How much did I spend last month ',
          ],
        },
        {
          name: 'addCategoryByDate',
          slots: [
            {
              name: 'category',
              type: 'CATEGORY',
              samples: [
                'I want to add restaurant category',
                'I want to add restaurant',
                'restaurant',
              ],
            },
            {
              name: 'date',
              type: 'AMAZON.DATE',
            },
            {
              name: 'categoryType',
              type: 'CATEGORY_TYPE',
              samples: [
                'I choose {categoryType}',
                'I want to choose {categoryType}',
                '{categoryType}',
              ],
            },
          ],
          samples: [
            'Add a restaurant category for September',
            'Add a restaurant category with {categoryType} for September',
            'Add a restaurant category for {categoryType} type',
            'Add a category for restaurant with {categoryType} type',
            'Add a category for shopping in {categoryType} type for September',
            'Add a category for shopping in {categoryType} type',
            'Add a category for shopping',
            'Add a new category for shopping in {categoryType} type',
            'Add a new category for shopping in {categoryType} type for September',
            'Add a new category for shopping in September',
            'Add a new category for shopping for September',
            'Add a new category for shopping with {categoryType} type for September',
            'Add a new category for shopping with {categoryType} type',
            'Add a new shopping category for the  {categoryType} type',
            'Add a new shopping category for {categoryType} type',
            'Add a new shopping category for the September',
            'Add a new shopping category with {categoryType} for the  September',
            'Add a new shopping category with {categoryType} for September',
            'Add a new learning category for September',
            'Add a new category for September',
            'Add a new category for learning',
          ],
        },
      ],
    },
  },
};
