# This workflow will do a Deployment to AWS LAMBDA
name: Deploy to AWS

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # processBlitzBudgetRecords (1)
    - name: processBlitzBudgetRecords zip
      run: cd DynamoDb-Stream/processBlitzBudgetTable/; zip -qq -r ../../processBlitzBudgetTable.zip ./; cd ../..;
    - name: processBlitzBudgetRecords deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: processBlitzBudgetRecords
        zip_file: processBlitzBudgetTable.zip
    # addAccounts (2)
    - name: addAccounts zip
      run: cd BlitzBudget/Accounts/addAccounts/; zip -qq -r ../../../addAccounts.zip ./; cd ../../..;
    - name: addAccounts deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addAccounts
        zip_file: addAccounts.zip
    # deleteAccounts (3)
    - name: deleteAccounts zip
      run: cd BlitzBudget/Accounts/deleteAccount/; zip -qq -r ../../../deleteAccounts.zip ./; cd ../../..;
    - name: deleteAccounts deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAccounts
        zip_file: deleteAccounts.zip
    # getAccounts (4)
    - name: getAccounts zip
      run: cd BlitzBudget/Accounts/getAccounts/; zip -qq -r ../../../getAccounts.zip ./; cd ../../..;
    - name: getAccounts deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: getAccounts
        zip_file: getAccounts.zip
    # patchAccounts (5)
    - name: getAccounts zip
      run: cd BlitzBudget/Accounts/patchAccount/; zip -qq -r ../../../patchAccount.zip ./; cd ../../..;
    - name: patchAccount deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchAccounts
        zip_file: patchAccount.zip
    # deleteCategory (9)
    - name: deleteCategory zip
      run: cd BlitzBudget/Category/deleteCategories/; zip -qq -r ../../../deleteCategory.zip ./; cd ../../..;
    - name: deleteCategory deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteCategory
        zip_file: deleteCategory.zip
    # deleteAllItemsFromWallet (10)
    - name: deleteAllItemsFromWallet zip
      run: cd BlitzBudget/Common/deleteAllItemsFromWallet/; zip -qq -r ../../../deleteAllItemsFromWallet.zip ./; cd ../../..;
    - name: deleteAllItemsFromWallet deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAllItemsFromWallet
        zip_file: deleteAllItemsFromWallet.zip
    # deleteAllWallets (11)
    - name: deleteAllWallets zip
      run: cd BlitzBudget/Common/deleteAllWallets/; zip -qq -r ../../../deleteAllWallets.zip ./; cd ../../..;
    - name: deleteAllWallets deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAllWallets
        zip_file: deleteAllWallets.zip
    # deleteMultipleItems (12)
    - name: deleteMultipleItems zip
      run: cd BlitzBudget/Common/deleteBatch/; zip -qq -r ../../../deleteMultipleItems.zip ./; cd ../../..;
    - name: deleteMultipleItems deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteMultipleItems
        zip_file: deleteMultipleItems.zip
    # deleteOneItem (13)
    - name: deleteOneItem zip
      run: cd BlitzBudget/Common/deleteOneItem/; zip -qq -r ../../../deleteOneItem.zip ./; cd ../../..;
    - name: deleteOneItem deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteOneItem
        zip_file: deleteOneItem.zip
    # resetAccountBB (18)
    - name: resetAccountBB zip
      run: cd BlitzBudget/Profile/reset-account-bb/; zip -qq -r ../../../resetAccountBB.zip ./; cd ../../..;
    - name: resetAccountBB deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: resetAccountBB
        zip_file: resetAccountBB.zip
    # sendEmailToSupport (19)
    - name: sendEmailToSupport zip
      run: cd BlitzBudget/Profile/sendEmailToSupport/; zip -qq -r ../../../sendEmailToSupport.zip ./; cd ../../..;
    - name: sendEmailToSupport deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: sendEmailToSupport
        zip_file: sendEmailToSupport.zip
    # addScheduledTransactions (20)
    - name: addScheduledTransactions zip
      run: cd BlitzBudget/RecurringTransactions/addScheduledTransactions/; zip -qq -r ../../../addScheduledTransactions.zip ./; cd ../../..;
    - name: addScheduledTransactions deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addScheduledTransactions
        zip_file: addScheduledTransactions.zip
    # patchRecurringTransaction (21)
    - name: patchRecurringTransaction zip
      run: cd BlitzBudget/RecurringTransactions/patchRecurringTransactions/; zip -qq -r ../../../patchRecurringTransaction.zip ./; cd ../../..;
    - name: patchRecurringTransaction deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchRecurringTransaction
        zip_file: patchRecurringTransaction.zip
    # adminGetUserAttributes (28)
    - name: adminGetUserAttributes zip
      run: cd Cognito/adminGetUserAttributes/; zip -qq -r ../../adminGetUserAttributes.zip ./; cd ../..;
    - name: adminGetUserAttributes deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: adminGetUserAttributes
        zip_file: adminGetUserAttributes.zip
    # adminUpdateAttributes (29)
    - name: adminUpdateAttributes zip
      run: cd Cognito/adminUpdateUserAttribute/; zip -qq -r ../../adminUpdateAttributes.zip ./; cd ../..;
    - name: adminUpdateAttributes deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: adminUpdateAttributes
        zip_file: adminUpdateAttributes.zip
    # changePassword (30)
    - name: changePassword zip
      run: cd Cognito/changePassword/; zip -qq -r ../../changePassword.zip ./; cd ../..;
    - name: changePassword deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: changePassword
        zip_file: changePassword.zip
    # confirmForgotPassword (31)
    - name: confirmForgotPassword zip
      run: cd Cognito/confirmForgotPassword/; zip -qq -r ../../confirmForgotPassword.zip ./; cd ../..;
    - name: confirmForgotPassword deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: confirmForgotPassword
        zip_file: confirmForgotPassword.zip
    # confirmSignup (32)
    - name: confirmSignup zip
      run: cd Cognito/confirmSignup/; zip -qq -r ../../confirmSignup.zip ./; cd ../..;
    - name: confirmSignup deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: confirmSignup
        zip_file: confirmSignup.zip
    # deleteUser (33)
    - name: deleteUser zip
      run: cd Cognito/deleteUser/; zip -qq -r ../../deleteUser.zip ./; cd ../..;
    - name: deleteUser deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteUser
        zip_file: deleteUser.zip
    # forgotPassword (34)
    - name: forgotPassword zip
      run: cd Cognito/forgotPassword/; zip -qq -r ../../forgotPassword.zip ./; cd ../..;
    - name: forgotPassword deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: forgotPassword
        zip_file: forgotPassword.zip
    # refreshToken (35)
    - name: refreshToken zip
      run: cd Cognito/refreshToken/; zip -qq -r ../../refreshToken.zip ./; cd ../..;
    - name: refreshToken deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: refreshToken
        zip_file: refreshToken.zip
    # resendConfirmationCode (36)
    - name: resendConfirmationCode zip
      run: cd Cognito/resendConfirmationCode/; zip -qq -r ../../resendConfirmationCode.zip ./; cd ../..;
    - name: resendConfirmationCode deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: resendConfirmationCode
        zip_file: resendConfirmationCode.zip
    # signin (37)
    - name: signin zip
      run: cd Cognito/signin/; zip -qq -r ../../signin.zip ./; cd ../..;
    - name: signin deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: signin
        zip_file: signin.zip
    # signup (38)
    - name: signup zip
      run: cd Cognito/signup/; zip -qq -r ../../signup.zip ./; cd ../..;
    - name: signup deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: signup
        zip_file: signup.zip
    
