# This workflow will do a Deployment to AWS LAMBDA
name: Deploy to AWS

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # deleteCategory (9)
    - name: deleteCategory zip
      run: cd BlitzBudget/Category/deleteCategories/; zip -qq -r ../../../deleteCategory.zip ./; cd ../../..;
    - name: deleteCategory deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteCategory
        zip_file: deleteCategory.zip
    # deleteAllItemsFromWallet (10)
    - name: deleteAllItemsFromWallet zip
      run: cd BlitzBudget/Common/deleteAllItemsFromWallet/; zip -qq -r ../../../deleteAllItemsFromWallet.zip ./; cd ../../..;
    - name: deleteAllItemsFromWallet deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAllItemsFromWallet
        zip_file: deleteAllItemsFromWallet.zip
    # deleteAllWallets (11)
    - name: deleteAllWallets zip
      run: cd BlitzBudget/Common/deleteAllWallets/; zip -qq -r ../../../deleteAllWallets.zip ./; cd ../../..;
    - name: deleteAllWallets deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAllWallets
        zip_file: deleteAllWallets.zip
    # deleteMultipleItems (12)
    - name: deleteMultipleItems zip
      run: cd BlitzBudget/Common/deleteBatch/; zip -qq -r ../../../deleteMultipleItems.zip ./; cd ../../..;
    - name: deleteMultipleItems deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteMultipleItems
        zip_file: deleteMultipleItems.zip
    # deleteOneItem (13)
    - name: deleteOneItem zip
      run: cd BlitzBudget/Common/deleteOneItem/; zip -qq -r ../../../deleteOneItem.zip ./; cd ../../..;
    - name: deleteOneItem deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteOneItem
        zip_file: deleteOneItem.zip
    # resetAccountBB (18)
    - name: resetAccountBB zip
      run: cd BlitzBudget/Profile/reset-account-bb/; zip -qq -r ../../../resetAccountBB.zip ./; cd ../../..;
    - name: resetAccountBB deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: resetAccount
        zip_file: resetAccountBB.zip
    # sendEmailToSupport (19)
    - name: sendEmailToSupport zip
      run: cd BlitzBudget/Profile/sendEmailToSupport/; zip -qq -r ../../../sendEmailToSupport.zip ./; cd ../../..;
    - name: sendEmailToSupport deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: sendEmailToSupport
        zip_file: sendEmailToSupport.zip
    # deleteUser (33)
    - name: deleteUser zip
      run: cd Cognito/deleteUser/; zip -qq -r ../../deleteUser.zip ./; cd ../..;
    - name: deleteUser deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteUser
        zip_file: deleteUser.zip
    
