# This workflow will do a Deployment to AWS LAMBDA
name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # processBlitzBudgetRecords (1)
    - name: processBlitzBudgetRecords zip
      run: cd DynamoDb-Stream/processBlitzBudgetTable/; zip -qq -r ../../processBlitzBudgetTable.zip ./; cd ../..;
    - name: processBlitzBudgetRecords deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: processBlitzBudgetRecords
        zip_file: processBlitzBudgetTable.zip
    # addAccounts (2)
    - name: addAccounts zip
      run: cd BlitzBudget/Accounts/addAccounts/; zip -qq -r ../../../addAccounts.zip ./; cd ../../..;
    - name: addAccounts deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addAccounts
        zip_file: addAccounts.zip
    # deleteAccounts (3)
    - name: deleteAccounts zip
      run: cd BlitzBudget/Accounts/deleteAccount/; zip -qq -r ../../../deleteAccounts.zip ./; cd ../../..;
    - name: deleteAccounts deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAccounts
        zip_file: deleteAccounts.zip
    # getAccounts (4)
    - name: getAccounts zip
      run: cd BlitzBudget/Accounts/getAccounts/; zip -qq -r ../../../getAccounts.zip ./; cd ../../..;
    - name: getAccounts deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: getAccounts
        zip_file: getAccounts.zip
    # patchAccounts (5)
    - name: getAccounts zip
      run: cd BlitzBudget/Accounts/patchAccount/; zip -qq -r ../../../patchAccount.zip ./; cd ../../..;
    - name: patchAccount deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchAccounts
        zip_file: patchAccount.zip
    # addBudget (6)
    - name: addBudget zip
      run: cd BlitzBudget/Budgets/addBudgets/; zip -qq -r ../../../addBudget.zip ./; cd ../../..;
    - name: addBudget deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addBudget
        zip_file: addBudget.zip
    # getBudget (7)
    - name: getBudget zip
      run: cd BlitzBudget/Budgets/getBudgets/; zip -qq -r ../../../getBudget.zip ./; cd ../../..;
    - name: getBudget deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: getBudget
        zip_file: getBudget.zip
    # patchBudget (8)
    - name: patchBudgets zip
      run: cd BlitzBudget/Budgets/patchBudgets/; zip -qq -r ../../../patchBudget.zip ./; cd ../../..;
    - name: patchBudget deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchBudget
        zip_file: patchBudget.zip
    # deleteCategory (9)
    - name: deleteCategory zip
      run: cd BlitzBudget/Category/deleteCategories/; zip -qq -r ../../../deleteCategory.zip ./; cd ../../..;
    - name: deleteCategory deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteCategory
        zip_file: deleteCategory.zip
    # deleteAllItemsFromWallet (10)
    - name: deleteAllItemsFromWallet zip
      run: cd BlitzBudget/Common/deleteAllItemsFromWallet/; zip -qq -r ../../../deleteAllItemsFromWallet.zip ./; cd ../../..;
    - name: deleteAllItemsFromWallet deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAllItemsFromWallet
        zip_file: deleteAllItemsFromWallet.zip
    # deleteAllWallets (11)
    - name: deleteAllWallets zip
      run: cd BlitzBudget/Common/deleteAllWallets/; zip -qq -r ../../../deleteAllWallets.zip ./; cd ../../..;
    - name: deleteAllWallets deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteAllWallets
        zip_file: deleteAllWallets.zip
    # deleteMultipleItems (12)
    - name: deleteMultipleItems zip
      run: cd BlitzBudget/Common/deleteBatch/; zip -qq -r ../../../deleteMultipleItems.zip ./; cd ../../..;
    - name: deleteMultipleItems deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteMultipleItems
        zip_file: deleteMultipleItems.zip
    # deleteOneItem (13)
    - name: deleteOneItem zip
      run: cd BlitzBudget/Common/deleteOneItem/; zip -qq -r ../../../deleteOneItem.zip ./; cd ../../..;
    - name: deleteOneItem deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: deleteOneItem
        zip_file: deleteOneItem.zip
    # addGoals (14)
    - name: addGoals zip
      run: cd BlitzBudget/Goals/addGoals/; zip -qq -r ../../../addGoals.zip ./; cd ../../..;
    - name: addGoals deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addGoals
        zip_file: addGoals.zip
    # getGoals (15)
    - name: getGoals zip
      run: cd BlitzBudget/Goals/getGoals/; zip -qq -r ../../../getGoals.zip ./; cd ../../..;
    - name: getGoals deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: getGoals
        zip_file: getGoals.zip
    # patchGoal (16)
    - name: patchGoal zip
      run: cd BlitzBudget/Goals/patchGoals/; zip -qq -r ../../../patchGoal.zip ./; cd ../../..;
    - name: patchGoal deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchGoal
        zip_file: patchGoal.zip
    # getOverview (17)
    - name: getOverview zip
      run: cd BlitzBudget/Overview/; zip -qq -r ../../../getOverview.zip ./; cd ../../..;
    - name: getOverview deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: getOverview
        zip_file: getOverview.zip
    # resetAccountBB (18)
    - name: resetAccountBB zip
      run: cd BlitzBudget/Profile/reset-account-bb/; zip -qq -r ../../../resetAccountBB.zip ./; cd ../../..;
    - name: resetAccountBB deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: resetAccountBB
        zip_file: resetAccountBB.zip
    # sendEmailToSupport (19)
    - name: sendEmailToSupport zip
      run: cd BlitzBudget/Profile/sendEmailToSupport/; zip -qq -r ../../../sendEmailToSupport.zip ./; cd ../../..;
    - name: sendEmailToSupport deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: sendEmailToSupport
        zip_file: sendEmailToSupport.zip
    # addScheduledTransactions (20)
    - name: addScheduledTransactions zip
      run: cd BlitzBudget/RecurringTransactions/addScheduledTransactions/; zip -qq -r ../../../addScheduledTransactions.zip ./; cd ../../..;
    - name: addScheduledTransactions deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addScheduledTransactions
        zip_file: addScheduledTransactions.zip
    # patchRecurringTransaction (21)
    - name: patchRecurringTransaction zip
      run: cd BlitzBudget/RecurringTransactions/patchRecurringTransaction/; zip -qq -r ../../../patchRecurringTransaction.zip ./; cd ../../..;
    - name: patchRecurringTransaction deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchRecurringTransaction
        zip_file: patchRecurringTransaction.zip
    # addTransactions (22)
    - name: addTransactions zip
      run: cd BlitzBudget/RecurringTransactions/addTransactions/; zip -qq -r ../../../addTransactions.zip ./; cd ../../..;
    - name: addTransactions deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addTransactions
        zip_file: addTransactions.zip
    # getTransactions (23)
    - name: getTransactions zip
      run: cd BlitzBudget/Transactions/getTransactions/; zip -qq -r ../../../getTransactions.zip ./; cd ../../..;
    - name: getTransactions deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: getTransactions
        zip_file: getTransactions.zip
    # patchTransactions (24)
    - name: patchTransactions zip
      run: cd BlitzBudget/Transactions/patchTransactions/; zip -qq -r ../../../patchTransactions.zip ./; cd ../../..;
    - name: patchTransactions deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchTransactions
        zip_file: patchTransactions.zip
    # addWallet (25)
    - name: addWallet zip
      run: cd BlitzBudget/Transactions/addWallet/; zip -qq -r ../../../addWallet.zip ./; cd ../../..;
    - name: addWallet deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: addWallet
        zip_file: addWallet.zip
    # getWallet (26)
    - name: getWallet zip
      run: cd BlitzBudget/Wallets/getWallet/; zip -qq -r ../../../getWallet.zip ./; cd ../../..;
    - name: getWallet deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: getWallet
        zip_file: getWallet.zip
    # patchWallet (27)
    - name: patchWallet zip
      run: cd BlitzBudget/Wallets/patchWallet/; zip -qq -r ../../../patchWallet.zip ./; cd ../../..;
    - name: patchWallet deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: patchWallet
        zip_file: patchWallet.zip